name: Run Ktlint and Tests

on:
  pull_request:
    paths:
      - '**/*.kt'
      - '**/*.kts'
  push:
    branches:
      - main
    paths:
      - '**/*.kt'
      - '**/*.kts'
  workflow_dispatch:

jobs:
  ktlint_and_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd="pg_isready -U user -d testdb"
          --health-timeout=5s
          --health-interval=5s
          --health-retries=5

    steps:
      # Check out the code from the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Install dependencies using Gradle
      - name: Install dependencies
        run: ./gradlew build --no-daemon

      # Run Ktlint check
      - name: Run Ktlint
        run: ./gradlew ktlintCheck --no-daemon

      # Run tests
      - name: Run tests
        run: ./gradlew test --no-daemon
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: password
          SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
