name: Run Ktlint

on:
  pull_request:
    paths:
      - '**/*.kt'
      - '**/*.kts'
  push:
    branches:
      - main
    paths:
      - '**/*.kt'
      - '**/*.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set up JDK 21 (matching your Java version)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Install dependencies (including ktlint) using Gradle
      - name: Install dependencies
        run: ./gradlew build

      # Run ktlint check
      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      # Optional: Fail the job if ktlint check fails
      - name: Fail if Ktlint fails
        run: ./gradlew ktlintCheck --continue
